version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '07:00'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 99
    assignees:
      - ffflorian
    versioning-strategy: increase
    ignore:
      - dependency-name: '@types/node'
        versions:
          - '> 16.a'
      - dependency-name: 'package-json'
        versions:
          - '>= 7.x'
      - dependency-name: 'find-up'
        versions:
          - '>= 6.a'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 99
    assignees:
      - ffflorian
